repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi]

      - id: ruff
        name: ruff-lint
        entry: ruff check --force-exclude
        language: python
        types_or: [ python, pyi ]
        require_serial: true

#      - id: pytest-check
#        name: pytest-check
#        entry: poetry run pytest
#        language: system
#        pass_filenames: false
#        always_run: true
