[tool.poetry]
name = "subject-to-change"
version = "0.1.0"
description = ""
authors = ["ArtemKhel <ArtemKhel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "^1.26.1"
matplotlib = "^3.8.0"
jupyter = "^1.0.0"
seaborn = "^0.13.0"
#scipy = "^1.11.3"
#sklearn = "^0.0.post10"
pandas = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
