name: "Sphinx: Render docs"

on: push

jobs:
  sphinx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with:
          build-command: "make --directory docs/ html"
          docs-folder: "docs/"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: docs/build/html
